/**
 * test_pipeline.js
 * ─────────────────────────────────────────────────────────────────────────────
 * End-to-end pipeline tests. Does NOT connect to Drake, CCH, or the companion.
 *
 * Coverage:
 *   1. TaxLoader (legacy) — parse / validate / generateFileOnly for all entity types
 *   2. DrakeLoader (new)  — generateFiles() for all entity types + 8949/4562
 *   3. Trial Balance balance assertion (debits = credits)
 *   4. Form 8949 date format validation
 *   5. Form 4562 column structure
 *   6. Schedule C CSV structure for 1040
 *   7. Field map coverage (all canonical keys present in all 8 field maps)
 */

const assert  = require('assert');
const fs      = require('fs');
const path    = require('path');
const ExcelJS = require('exceljs');

const { TaxLoader, DrakeLoader } = require('../index');
const { keysFor }       = require('../lib/canonical');
const { checkBalance }  = require('../generators/trialBalanceGenerator');
const { validateDates } = require('../generators/form8949Generator');

const TMP_DIR = path.join(__dirname, '.tmp');
const ENTITIES = ['1040', '1065', '1120', '1120S'];

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

function ensureTmp() {
  fs.rmSync(TMP_DIR, { recursive: true, force: true });
  fs.mkdirSync(TMP_DIR, { recursive: true });
}

function sampleEin(entityType) {
  return entityType === '1040' ? '123-45-6789' : '82-1234567';
}

async function createWorkbook(entityType) {
  const wb   = new ExcelJS.Workbook();
  const cover = wb.addWorksheet('Cover');
  cover.addRows([
    ['Client', `Example ${entityType} Client`],
    ['EIN',    sampleEin(entityType)],
    ['Entity', entityType],
    ['Year',   2025],
  ]);

  const data = wb.addWorksheet('Federal Data');
  data.addRow(['Generated by test']);
  data.addRow([]);
  data.addRow(['QBO Account', 'Tax Amount', 'canonical_key', 'flag', 'CPA Notes']);

  const keys = Object.keys(keysFor(entityType));
  assert(keys.length > 4, `expected canonical keys for ${entityType}`);

  keys.slice(0, 6).forEach((key, index) => {
    const flag = index === 1 ? 'review' : index === 5 ? 'manual' : 'ok';
    data.addRow([`Account ${index + 1}`, (index + 1) * 10000, key, flag,
                 flag === 'review' ? 'CPA confirmed' : '']);
  });

  data.addRow(['Unknown', 999, 'unknown.not_loadable', 'ok', 'should be ignored']);

  const filePath = path.join(TMP_DIR, `approved_${entityType}.xlsx`);
  await wb.xlsx.writeFile(filePath);
  return { filePath, keys };
}

function assertMapCoverage(entityType, software) {
  const mapPath = path.join(__dirname, '..', 'fieldMaps', `${software}_${entityType}.json`);
  const map     = JSON.parse(fs.readFileSync(mapPath, 'utf8'));
  const expectedKeys = Object.keys(keysFor(entityType));
  const missing = expectedKeys.filter(key => !map.map || !map.map[key]);
  assert.deepStrictEqual(missing, [], `${software}_${entityType} missing canonical keys: ${missing.join(', ')}`);
}

// ─────────────────────────────────────────────────────────────────────────────
// Section 1: TaxLoader (legacy) tests
// ─────────────────────────────────────────────────────────────────────────────

async function testLegacyEntity(entityType) {
  const loader = new TaxLoader();
  const { filePath, keys } = await createWorkbook(entityType);
  const parsed = await loader.parseWorkpaper(filePath);

  // Parsing
  assert.strictEqual(parsed.client.entityType, entityType);
  assert.strictEqual(parsed.taxYear, 2025);
  assert.strictEqual(parsed.client.name, `Example ${entityType} Client`);
  assert.strictEqual(parsed.fields.length, 6, 'unknown canonical keys must be ignored');

  // Validation
  const validation = loader.validate(parsed);
  assert.strictEqual(validation.ok, true, 'review/manual should not block');
  assert(validation.warnings.some(w => w.includes('REVIEW')), 'review flag should warn');
  assert(validation.warnings.some(w => w.includes('MANUAL')), 'manual flag should warn');

  // Error flag blocks
  const blocked = loader.validate({
    ...parsed,
    fields: parsed.fields.concat({
      canonicalKey: keys[0], value: 123, flag: 'error',
      sourceTab: 'Federal Data', note: 'intentional blocker',
    }),
  });
  assert.strictEqual(blocked.ok, false, 'error flag must block');
  assert(blocked.blockers.some(b => b.includes('intentional blocker')));

  // CCH Axcess artifact
  const cch = await loader.generateFileOnly('cch_axcess', parsed);
  assert.strictEqual(cch.kind, 'api_payload');
  assert.strictEqual(cch.software, 'cch_axcess');
  assert.strictEqual(cch.meta.fieldCount, 5, 'manual field must be skipped in CCH');
  assert.strictEqual(cch.content.fields.length, 5);
  assert(cch.meta.skipped.includes(parsed.fields[5].canonicalKey));

  // Drake artifact (legacy adapter)
  const drake = await loader.generateFileOnly('drake', parsed);
  assert.strictEqual(drake.software, 'drake');

  if (entityType === '1040') {
    // Legacy 1040 path → UI payload (drake_ui.py flow)
    assert.strictEqual(drake.kind, 'drake_1040_ui', '1040 legacy path returns UI payload');
    assert(drake.uiPayload, 'uiPayload must be present for 1040');
    // No fieldCount in UI-payload meta — that's expected
  } else {
    // Business entities → trial balance template artifact
    assert.strictEqual(drake.kind, 'drake_trial_balance_template');
    assert.strictEqual(drake.meta.fieldCount, 5, 'manual field must be skipped in Drake TB');
    assert(drake.filename.endsWith('.xls'));
    assert(drake.content.rows.length === 5);
    assert(drake.meta.templatePath.toLowerCase().includes('drake'));
  }

  // Field map coverage for both software providers
  assertMapCoverage(entityType, 'cch_axcess');
  assertMapCoverage(entityType, 'drake');
}

// ─────────────────────────────────────────────────────────────────────────────
// Section 2: DrakeLoader (new) tests
// ─────────────────────────────────────────────────────────────────────────────

async function testDrakeLoaderEntity(entityType) {
  // DrakeLoader with no companion URL (generateOnly mode)
  const loader = new DrakeLoader({ templateDir: TMP_DIR });
  const { filePath, keys } = await createWorkbook(entityType);

  // generateOnly — no companion needed
  const result = await loader.generateOnly(filePath);

  assert(result.data, 'data must be present');
  assert.strictEqual(result.data.client.entityType, entityType);
  assert(Array.isArray(result.warnings), 'warnings must be array');

  const files = result.files;

  if (['1120S', '1065', '1120'].includes(entityType)) {
    // Trial Balance must be present (synthetic mode — no real template in TMP_DIR)
    assert(files.trialBalance, `trialBalance must be generated for ${entityType}`);
    assert(Buffer.isBuffer(files.trialBalance.buffer), 'TB buffer must be a Buffer');
    assert(files.trialBalance.filename.endsWith('.xls'), 'TB filename must end with .xls');
    assert(files.trialBalance.meta.entityType === entityType);

    // Balance check
    const bal = files.trialBalance.meta;
    assert(typeof bal.totalDebits  === 'number', 'totalDebits must be a number');
    assert(typeof bal.totalCredits === 'number', 'totalCredits must be a number');
    // Note: balance will NOT be equal with synthetic data (test data is not a real TB)
    // We just verify the values are computed, not that they're equal.

    // No scheduleC for business entities
    assert.strictEqual(files.scheduleC, null, 'no scheduleC for business entity');
  }

  if (entityType === '1040') {
    // Schedule C CSV must be present
    assert(files.scheduleC, 'scheduleC must be generated for 1040');
    assert(typeof files.scheduleC.content === 'string', 'scheduleC must have content string');
    assert(files.scheduleC.filename.endsWith('.csv'), 'scheduleC must be a csv');
    assert(files.scheduleC.content.includes('Schedule_C_Line'), 'CSV must have Schedule_C_Line header');

    // Manual entry guide must be generated for 1040
    assert(files.manualEntryGuide, 'manualEntryGuide must be generated for 1040');
    assert(Buffer.isBuffer(files.manualEntryGuide.buffer), 'manualEntryGuide must have XLSX buffer');
    assert(files.manualEntryGuide.filename.endsWith('.xlsx'), 'manualEntryGuide must be xlsx');
    assert(files.manualEntryGuide.filename.includes('manual_entry'), 'filename must say manual_entry');
    assert(files.manualEntryGuide.meta.totalForms === 0, 'totalForms=0 when no W2/1099 data in workpaper');

    // No trial balance for 1040
    assert.strictEqual(files.trialBalance, null, 'no trialBalance for 1040');
  } else {
    // Business entities must NOT have a manual entry guide
    assert.strictEqual(files.manualEntryGuide, null, 'no manualEntryGuide for business entity');
  }

  // 8949 and 4562 are null when no extras provided
  assert.strictEqual(files.form8949, null, 'form8949 null when no transactions provided');
  assert.strictEqual(files.form4562, null, 'form4562 null when no assets provided');
}

async function testDrakeLoaderWith8949And4562() {
  const loader = new DrakeLoader({ templateDir: TMP_DIR });
  const { filePath } = await createWorkbook('1120S');

  const transactions8949 = [
    {
      description:  'Apple Inc AAPL',
      dateAcquired: '2024-01-15',
      dateSold:     '2024-11-20',
      proceeds:     25000,
      basis:        18000,
      form8949Box:  'A',
    },
    {
      description:  'Various Stocks',
      dateAcquired: 'VARIOUS',
      dateSold:     '12/31/2024',
      proceeds:     8000,
      basis:        9500,
      adjCode:      'W',
      adjAmount:    150,
      form8949Box:  'B',
    },
  ];

  const assets4562 = [
    { description: 'Server Equipment', dateInService: '2024-03-01', cost: 15000, method: 'DB', life: 5 },
    { description: 'Office Furniture',  dateInService: '2023-07-15', cost: 8000,  method: 'SL', life: 7, priorDepreciation: 1143 },
  ];

  const result = await loader.generateOnly(filePath, { transactions8949, assets4562 });
  const files  = result.files;

  // Form 8949
  assert(files.form8949, 'form8949 must be generated when transactions provided');
  assert(typeof files.form8949.content === 'string', 'form8949 must have CSV content');
  assert(files.form8949.filename.includes('8949'), 'form8949 filename must include 8949');

  // Date format validation
  // Drake requires MMDDYYYY (8-digit no-separator format) per DRAKEHLP.CHM
  const { valid, errors } = validateDates(transactions8949);
  assert(valid, `8949 dates must be valid MMDDYYYY: ${errors.join(', ')}`);

  // Verify dates are MMDDYYYY in the CSV (no slashes — Drake requirement)
  assert(files.form8949.content.includes('01152024'), 'ISO date must convert to MMDDYYYY');
  assert(files.form8949.content.includes('11202024'), 'sold date must be MMDDYYYY');
  assert(files.form8949.content.includes('VARIOUS'),  '"VARIOUS" must pass through unchanged');

  // Form 4562
  assert(files.form4562, 'form4562 must be generated when assets provided');
  assert(Buffer.isBuffer(files.form4562.buffer), 'form4562 must be a Buffer');
  assert(files.form4562.filename.includes('4562'), 'form4562 filename must include 4562');
  assert.strictEqual(files.form4562.meta.assetCount, 2, 'assetCount must match input');
}

async function testTrialBalanceBalance() {
  // Verify the balance-check utility works
  const balanced = [
    { debit: 1000, credit: null },
    { debit: null, credit: 1000 },
  ];
  const { balanced: isBalanced } = checkBalance(balanced);
  assert(isBalanced, 'equal debits/credits must be balanced');

  const unbalanced = [
    { debit: 1000, credit: null },
    { debit: null, credit: 999 },
  ];
  const { balanced: isUnbalanced } = checkBalance(unbalanced);
  assert(!isUnbalanced, 'unequal debits/credits must not be balanced');
}

// ─────────────────────────────────────────────────────────────────────────────
// Runner
// ─────────────────────────────────────────────────────────────────────────────

async function main() {
  ensureTmp();

  // Section 1: legacy TaxLoader
  for (const entityType of ENTITIES) {
    await testLegacyEntity(entityType);
    console.log(`[ok] TaxLoader   ${entityType}`);
  }

  // Section 2: new DrakeLoader
  for (const entityType of ENTITIES) {
    await testDrakeLoaderEntity(entityType);
    console.log(`[ok] DrakeLoader ${entityType}`);
  }

  // Section 3: DrakeLoader with 8949 + 4562 extras
  await testDrakeLoaderWith8949And4562();
  console.log('[ok] DrakeLoader  8949 + 4562');

  // Section 4: balance utility
  await testTrialBalanceBalance();
  console.log('[ok] Trial Balance balance check');

  console.log('\n✓ All tests passed');
}

main().catch(error => {
  console.error('[FAIL]', error.message);
  console.error(error.stack);
  process.exit(1);
});
