const assert = require("assert");
const fs = require("fs");
const path = require("path");
const ExcelJS = require("exceljs");

const { TaxLoader } = require("../index");
const { keysFor } = require("../lib/canonical");

const TMP_DIR = path.join(__dirname, ".tmp");
const ENTITIES = ["1040", "1065", "1120", "1120S"];

function ensureTmp() {
  fs.rmSync(TMP_DIR, { recursive: true, force: true });
  fs.mkdirSync(TMP_DIR, { recursive: true });
}

function sampleEin(entityType) {
  return entityType === "1040" ? "123-45-6789" : "82-1234567";
}

async function createWorkbook(entityType) {
  const wb = new ExcelJS.Workbook();
  const cover = wb.addWorksheet("Cover");
  cover.addRows([
    ["Client", `Example ${entityType} Client`],
    ["EIN", sampleEin(entityType)],
    ["Entity", entityType],
    ["Year", 2025],
  ]);

  const data = wb.addWorksheet("Federal Data");
  data.addRow(["Generated by test"]);
  data.addRow([]);
  data.addRow(["QBO Account", "Tax Amount", "canonical_key", "flag", "CPA Notes"]);

  const keys = Object.keys(keysFor(entityType));
  assert(keys.length > 4, `expected canonical keys for ${entityType}`);

  keys.slice(0, 6).forEach((key, index) => {
    const flag = index === 1 ? "review" : index === 5 ? "manual" : "ok";
    data.addRow([`Account ${index + 1}`, (index + 1) * 1000, key, flag, flag === "review" ? "CPA confirmed" : ""]);
  });

  data.addRow(["Unknown", 999, "unknown.not_loadable", "ok", "should be ignored"]);

  const filePath = path.join(TMP_DIR, `approved_${entityType}.xlsx`);
  await wb.xlsx.writeFile(filePath);
  return { filePath, keys };
}

function assertMapCoverage(entityType, software) {
  const mapPath = path.join(__dirname, "..", "fieldMaps", `${software}_${entityType}.json`);
  const map = JSON.parse(fs.readFileSync(mapPath, "utf8"));
  const expectedKeys = Object.keys(keysFor(entityType));
  const missing = expectedKeys.filter(key => !map.map || !map.map[key]);
  assert.deepStrictEqual(missing, [], `${software}_${entityType} missing canonical keys`);
}

async function testEntity(entityType) {
  const loader = new TaxLoader();
  const { filePath, keys } = await createWorkbook(entityType);
  const parsed = await loader.parseWorkpaper(filePath);

  assert.strictEqual(parsed.client.entityType, entityType);
  assert.strictEqual(parsed.taxYear, 2025);
  assert.strictEqual(parsed.client.name, `Example ${entityType} Client`);
  assert.strictEqual(parsed.fields.length, 6, "unknown canonical keys should be ignored");

  const validation = loader.validate(parsed);
  assert.strictEqual(validation.ok, true, "review/manual should not block loading");
  assert(validation.warnings.some(w => w.includes("REVIEW")), "review flag should warn");
  assert(validation.warnings.some(w => w.includes("MANUAL")), "manual flag should warn");

  const blocked = loader.validate({
    ...parsed,
    fields: parsed.fields.concat({
      canonicalKey: keys[0],
      value: 123,
      flag: "error",
      sourceTab: "Federal Data",
      note: "intentional blocker",
    }),
  });
  assert.strictEqual(blocked.ok, false, "error flag should block loading");
  assert(blocked.blockers.some(b => b.includes("intentional blocker")));

  const cch = await loader.generateFileOnly("cch_axcess", parsed);
  assert.strictEqual(cch.kind, "api_payload");
  assert.strictEqual(cch.software, "cch_axcess");
  assert.strictEqual(cch.meta.fieldCount, 5, "manual field should be skipped");
  assert.strictEqual(cch.content.fields.length, 5);
  assert(cch.meta.skipped.includes(parsed.fields[5].canonicalKey));

  const drake = await loader.generateFileOnly("drake", parsed);
  assert.strictEqual(drake.kind, "csv");
  assert.strictEqual(drake.software, "drake");
  assert.strictEqual(drake.meta.fieldCount, 5, "manual field should be skipped");
  assert(drake.content.includes("REQUIERE-DOC-OFICIAL"));
  assert(!drake.content.includes("Account 6"));

  if (entityType === "1040") {
    assert(drake.filename.startsWith("schedule_c_"));
  } else {
    assert(drake.filename.startsWith("trial_balance_"));
  }

  assertMapCoverage(entityType, "cch_axcess");
  assertMapCoverage(entityType, "drake");
}

async function main() {
  ensureTmp();
  for (const entityType of ENTITIES) {
    await testEntity(entityType);
    console.log(`[ok] ${entityType}`);
  }
  console.log("tax-loader test pipeline passed");
}

main().catch(error => {
  console.error(error);
  process.exit(1);
});
